# Generated by Django 6.0.4 on 2026-04-25 02:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('historial', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='historial',
            table='historial_actividad',
        ),
    ]
