# Generated by Django 5.1.5 on 2026-06-12 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historial', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historial',
            name='elemento_id',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='ID del Elemento'),
        ),
    ]
