# Generated by Django 6.0.4 on 2026-04-25 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('historial', '0002_alter_historial_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historial',
            options={'ordering': ['-fecha_hora'], 'verbose_name': 'Historial de Actividad', 'verbose_name_plural': 'Historial de Actividades'},
        ),
    ]
