# Generated by Django 6.0.4 on 2026-04-25 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0003_alter_factura_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='sincronizado',
            field=models.BooleanField(default=False),
        ),
    ]
