# Generated by Django 5.1.5 on 2026-07-08 22:10

import django.core.validators
import inventario.models.lotes
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_conteoitem_lotematerial_sesionconteo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lotematerial',
            name='cantidad',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='lotematerial',
            name='fecha_vencimiento',
            field=models.DateField(blank=True, db_index=True, null=True, validators=[inventario.models.lotes.validar_fecha_no_pasada]),
        ),
    ]
