# Generated by Django 5.1.5 on 2026-08-11 15:42

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0005_alter_compra_proveedor_alter_compra_usuario_and_more'),
        ('inventario', '0004_alter_lotematerial_cantidad_and_more'),
        ('ordenes', '0005_entrega_conductor_usuario_pedido_catalogo_and_more'),
        ('usuarios', '0007_rol_usuariorol_vehiculo_catalogo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movimientoinventario',
            options={'ordering': ['-fecha_movimiento']},
        ),
        migrations.RemoveIndex(
            model_name='movimientoinventario',
            name='movimiento__materia_f9ed93_idx',
        ),
        migrations.AddField(
            model_name='movimientoinventario',
            name='fecha_movimiento',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='movimientoinventario',
            name='fecha',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='movimientoinventario',
            name='material',
            field=models.ForeignKey(db_column='cod_material', on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='usuarios.materialconstruccion'),
        ),
        migrations.AlterField(
            model_name='movimientoinventario',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='movimientoinventario',
            index=models.Index(fields=['material', 'fecha_movimiento'], name='movimiento__cod_mat_5cbe83_idx'),
        ),
    ]
