# Generated by Django 5.1.5 on 2026-06-01 13:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('ordenes', '0001_initial'),
        ('usuarios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='detallepedido',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='usuarios.materialconstruccion'),
        ),
        migrations.AddField(
            model_name='entrega',
            name='conductor',
            field=models.ForeignKey(limit_choices_to={'rol': 'conductor'}, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='entrega',
            name='vehiculo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.vehiculo'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to='clientes.cliente'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='conductor',
            field=models.ForeignKey(blank=True, limit_choices_to={'rol': 'conductor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos_conductor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pedido',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='entrega',
            name='pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entregas', to='ordenes.pedido'),
        ),
        migrations.AddField(
            model_name='detallepedido',
            name='pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='ordenes.pedido'),
        ),
    ]
