# Generated by Django 6.0.4 on 2026-04-25 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrega',
            name='fecha_finalizacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterModelTable(
            name='detalleorden',
            table='detalles_orden',
        ),
        migrations.AlterModelTable(
            name='entrega',
            table='entregas',
        ),
        migrations.AlterModelTable(
            name='orden',
            table='ordenes',
        ),
    ]
