# Generated by Django 6.0.4 on 2026-04-25 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0002_entrega_fecha_finalizacion_alter_detalleorden_table_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='detalleorden',
            table='detalle_orden',
        ),
        migrations.AlterModelTable(
            name='entrega',
            table='entrega',
        ),
        migrations.AlterModelTable(
            name='orden',
            table='orden',
        ),
    ]
