# Generated by Django 6.0.4 on 2026-04-09 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0002_alter_detalleorden_cantidad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='confirmado_cliente',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orden',
            name='fecha_confirmacion_cliente',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
