# Generated by Django 6.0.4 on 2026-04-14 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0002_alter_detalleorden_cantidad_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orden',
            old_name='precio',
            new_name='total_pagar',
        ),
    ]
