# Generated by Django 6.0.4 on 2026-04-25 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0003_alter_detalleorden_table_alter_entrega_table_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrega',
            name='sincronizado',
            field=models.BooleanField(default=False),
        ),
    ]
