# Generated by Django 5.1.5 on 2026-05-10 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0005_orden_metodo_pago'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entrega',
            options={'ordering': ['-fecha_salida']},
        ),
        migrations.RenameField(
            model_name='entrega',
            old_name='fecha_finalizacion',
            new_name='fecha_entrega',
        ),
        migrations.RemoveField(
            model_name='entrega',
            name='fecha',
        ),
        migrations.AddField(
            model_name='entrega',
            name='direccion_entrega',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='entrega',
            name='fecha_salida',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
