# Generated by Django 5.1.5 on 2026-08-12 16:50

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0002_alter_cliente_options_cliente_direccion_and_more'),
        ('facturacion', '0003_factura_cliente_usuario_alter_factura_cliente_and_more'),
        ('ordenes', '0006_fix_db_column_duplicados'),
        ('usuarios', '0007_rol_usuariorol_vehiculo_catalogo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PagoPedido',
            fields=[
                ('id_pago_pedido', models.AutoField(primary_key=True, serialize=False)),
                ('metodo_pago', models.CharField(blank=True, db_column='metodo_pago_legacy', default='', max_length=80)),
                ('estado_pago', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_revision', 'En revisión'), ('pago aprobado', 'Pago aprobado'), ('pago rechazado', 'Pago rechazado'), ('contra_entrega', 'Contra entrega')], default='pendiente', max_length=30)),
                ('monto', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('referencia', models.CharField(blank=True, default='', max_length=120)),
                ('comprobante', models.FileField(blank=True, null=True, upload_to='comprobantes_pagos/%Y/%m/%d/')),
                ('motivo_rechazo', models.TextField(blank=True, default='')),
                ('historial', models.JSONField(blank=True, default=list)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos_pedido', to='clientes.cliente')),
                ('metodo_pago_fk', models.ForeignKey(blank=True, db_column='codigo_metodo_pago', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pagos_pedido', to='usuarios.metodopago')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos_pedido', to='ordenes.pedido')),
            ],
            options={
                'db_table': 'pago_pedido',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id_pago', models.AutoField(primary_key=True, serialize=False)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('referencia', models.CharField(blank=True, max_length=100)),
                ('sincronizado', models.BooleanField(default=False)),
                ('codigo_metodo_pago', models.ForeignKey(db_column='codigo_metodo_pago', on_delete=django.db.models.deletion.PROTECT, to='usuarios.metodopago')),
                ('factura', models.ForeignKey(db_column='id_factura', on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='facturacion.factura')),
                ('registrado_por', models.ForeignKey(db_column='registrado_por_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos_registrados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pago',
                'constraints': [models.CheckConstraint(condition=models.Q(('monto__gt', 0)), name='chk_pago_monto_gt_0')],
            },
        ),
    ]
