# Generated by Django 5.1.5 on 2026-06-09 15:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("facturacion", "0002_initial"),
        ("pagos", "0001_initial"),
        ("usuarios", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    # These fields are already present in pagos.0001_initial.
    operations = []
