# Generated by Django 5.1.5 on 2026-08-25 00:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pago',
            options={'permissions': (('registrar_pago', 'Puede registrar pagos'), ('reversar_pago', 'Puede reversar pagos'))},
        ),
    ]
