# Generated by Django 5.1.5 on 2026-07-02 14:05
# Generated by Django 5.1.5 on 2026-07-08 22:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='monto',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
    ]
