# Generated by Django 5.1.5 on 2026-09-09 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0002_alter_pago_options'),
        ('pagos', '0002_initial'),
        ('pagos', '0002_normalize_metodo_pago_fk'),
    ]

    operations = [
    ]
