# Generated by Django 5.1.5 on 2026-07-08 23:11

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
        ('ordenes', '0003_alter_detallepedido_precio_unitario_and_more'),
        ('pagos', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='monto',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
        migrations.CreateModel(
            name='PagoPedido',
            fields=[
                ('id_pago_pedido', models.AutoField(primary_key=True, serialize=False)),
                ('metodo_pago', models.CharField(blank=True, default='', max_length=80)),
                ('estado_pago', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_revision', 'En revisión'), ('pago aprobado', 'Pago aprobado'), ('pago rechazado', 'Pago rechazado'), ('contra_entrega', 'Contra entrega')], default='pendiente', max_length=30)),
                ('monto', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('referencia', models.CharField(blank=True, default='', max_length=120)),
                ('comprobante', models.FileField(blank=True, null=True, upload_to='comprobantes_pagos/%Y/%m/%d/')),
                ('motivo_rechazo', models.TextField(blank=True, default='')),
                ('historial', models.JSONField(blank=True, default=list)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos_pedido', to='clientes.cliente')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos_pedido', to='ordenes.pedido')),
            ],
            options={
                'db_table': 'pago_pedido',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
