# Generated by Django 5.1.5 on 2026-09-09 15:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0006_remove_factura_chk_factura_subtotal_gte_0_and_more'),
        ('pagos', '0003_merge_20260909_0900'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    # The current PagoPedido state already uses metodo_pago_fk and metodo_pago.
    operations = []
