# Generated by Django 5.1.5 on 2026-07-09 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0003_alter_pago_monto'),
        ('pagos', '0003_alter_pago_monto_pagopedido'),
    ]

    operations = [
    ]
