# Generated by Django 5.1.5 on 2026-09-16 13:24

from django.db import migrations, models


def add_evidencia_column(apps, schema_editor):
    pago_model = apps.get_model("pagos", "Pago")
    column_names = {
        column.name
        for column in schema_editor.connection.introspection.get_table_description(
            schema_editor.connection.cursor(), pago_model._meta.db_table
        )
    }
    field = models.ImageField(
        name="evidencia_fotografica",
        blank=True,
        null=True,
        upload_to="evidencias_pagos/%Y/%m/%d/",
    )
    field.model = pago_model
    field.set_attributes_from_name(field.name)
    if field.column not in column_names:
        schema_editor.add_field(pago_model, field)


def remove_evidencia_column(apps, schema_editor):
    pago_model = apps.get_model("pagos", "Pago")
    column_names = {
        column.name
        for column in schema_editor.connection.introspection.get_table_description(
            schema_editor.connection.cursor(), pago_model._meta.db_table
        )
    }
    field = pago_model._meta.get_field("evidencia_fotografica")
    if field.column in column_names:
        schema_editor.remove_field(pago_model, field)


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0004_remove_pagopedido_codigo_metodo_pago_and_more'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(
                    add_evidencia_column,
                    remove_evidencia_column,
                ),
            ],
            state_operations=[
                migrations.AddField(
                    model_name='pago',
                    name='evidencia_fotografica',
                    field=models.ImageField(
                        blank=True,
                        null=True,
                        upload_to='evidencias_pagos/%Y/%m/%d/',
                    ),
                ),
            ],
        ),
    ]
