# Generated by Django 5.1.5 on 2026-08-11 15:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0003_factura_cliente_usuario_alter_factura_cliente_and_more'),
        ('pagos', '0005_merge_0004_pagos'),
        ('usuarios', '0007_rol_usuariorol_vehiculo_catalogo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pagopedido',
            name='metodo_pago_fk',
            field=models.ForeignKey(blank=True, db_column='codigo_metodo_pago', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pagos_pedido', to='usuarios.metodopago'),
        ),
        migrations.AlterField(
            model_name='pago',
            name='factura',
            field=models.ForeignKey(db_column='id_factura', on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='facturacion.factura'),
        ),
        migrations.AlterField(
            model_name='pago',
            name='registrado_por',
            field=models.ForeignKey(db_column='registrado_por_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos_registrados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pagopedido',
            name='metodo_pago',
            field=models.CharField(blank=True, db_column='metodo_pago_legacy', default='', max_length=80),
        ),
        migrations.AddConstraint(
            model_name='pago',
            constraint=models.CheckConstraint(condition=models.Q(('monto__gt', 0)), name='chk_pago_monto_gt_0'),
        ),
    ]
