# Generated by Django 5.1.5 on 2026-08-11 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0004_merge_20260709_1155'),
        ('pagos', '0006_pagopedido_metodo_pago_fk_alter_pago_factura_and_more'),
    ]

    operations = [
    ]
