BEGIN;

CREATE TABLE IF NOT EXISTS "stock" (
    "material_id" integer NOT NULL PRIMARY KEY,
    "cantidad_actual" integer NOT NULL,
    "stock_minimo" integer NOT NULL,
    "ubicacion" varchar(120) NOT NULL,
    "fecha_actualizacion" timestamp with time zone NOT NULL
);
ALTER TABLE "stock"
    ADD CONSTRAINT "stock_material_id_11b6a7cf_fk_material_"
    FOREIGN KEY ("material_id") REFERENCES "material_construccion" ("cod_material")
    DEFERRABLE INITIALLY DEFERRED;

CREATE TABLE IF NOT EXISTS "sesion_conteo" (
    "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "codigo" varchar(50) NOT NULL UNIQUE,
    "fecha_inicio" timestamp with time zone NOT NULL,
    "fecha_fin" timestamp with time zone NULL,
    "estado" varchar(20) NOT NULL,
    "observaciones" text NOT NULL
);

CREATE TABLE IF NOT EXISTS "conteo_item" (
    "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "cantidad_sistema" integer NOT NULL CHECK ("cantidad_sistema" >= 0),
    "cantidad_fisica" integer NOT NULL CHECK ("cantidad_fisica" >= 0),
    "diferencia" integer NOT NULL,
    "observaciones" text NOT NULL,
    "fecha_conteo" timestamp with time zone NOT NULL
);

CREATE TABLE IF NOT EXISTS "lote_material" (
    "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "codigo_lote" varchar(50) NOT NULL UNIQUE,
    "cantidad" integer NOT NULL CHECK ("cantidad" >= 0),
    "fecha_entrada" timestamp with time zone NOT NULL,
    "fecha_vencimiento" date NULL,
    "activo" boolean NOT NULL
);

ALTER TABLE "conteo_item" ADD COLUMN "material_id" integer NOT NULL
    CONSTRAINT "conteo_item_material_id_8c21b1b7_fk_material_"
    REFERENCES "material_construccion"("cod_material") DEFERRABLE INITIALLY DEFERRED;
SET CONSTRAINTS "conteo_item_material_id_8c21b1b7_fk_material_" IMMEDIATE;

ALTER TABLE "lote_material" ADD COLUMN "material_id" integer NOT NULL
    CONSTRAINT "lote_material_material_id_c7c3a3b6_fk_material_"
    REFERENCES "material_construccion"("cod_material") DEFERRABLE INITIALLY DEFERRED;
SET CONSTRAINTS "lote_material_material_id_c7c3a3b6_fk_material_" IMMEDIATE;

ALTER TABLE "sesion_conteo" ADD COLUMN "usuario_responsable_id" bigint NULL
    CONSTRAINT "sesion_conteo_usuario_responsable_id_25609e0d_fk_usuario_id"
    REFERENCES "usuario"("id") DEFERRABLE INITIALLY DEFERRED;
SET CONSTRAINTS "sesion_conteo_usuario_responsable_id_25609e0d_fk_usuario_id" IMMEDIATE;

ALTER TABLE "conteo_item" ADD COLUMN "sesion_id" bigint NOT NULL
    CONSTRAINT "conteo_item_sesion_id_44701d66_fk_sesion_conteo_id"
    REFERENCES "sesion_conteo"("id") DEFERRABLE INITIALLY DEFERRED;
SET CONSTRAINTS "conteo_item_sesion_id_44701d66_fk_sesion_conteo_id" IMMEDIATE;

ALTER TABLE "conteo_item"
    ADD CONSTRAINT "conteo_item_sesion_id_material_id_bd2f38a2_uniq"
    UNIQUE ("sesion_id", "material_id");

CREATE INDEX IF NOT EXISTS "lote_material_codigo_lote_e25d70da_like" ON "lote_material" ("codigo_lote" varchar_pattern_ops);
CREATE INDEX IF NOT EXISTS "lote_material_fecha_vencimiento_91ec8084" ON "lote_material" ("fecha_vencimiento");
CREATE INDEX IF NOT EXISTS "sesion_conteo_codigo_64ecc7b5_like" ON "sesion_conteo" ("codigo" varchar_pattern_ops);
CREATE INDEX IF NOT EXISTS "conteo_item_material_id_8c21b1b7" ON "conteo_item" ("material_id");
CREATE INDEX IF NOT EXISTS "lote_material_material_id_c7c3a3b6" ON "lote_material" ("material_id");
CREATE INDEX IF NOT EXISTS "sesion_conteo_usuario_responsable_id_25609e0d" ON "sesion_conteo" ("usuario_responsable_id");
CREATE INDEX IF NOT EXISTS "conteo_item_sesion_id_44701d66" ON "conteo_item" ("sesion_id");

CREATE TABLE IF NOT EXISTS "gestion_pedido" (
    "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "fecha_creacion" timestamp with time zone NOT NULL,
    "estado" varchar(12) NOT NULL,
    "descuento" numeric(10, 2) NOT NULL,
    "total" numeric(12, 2) NOT NULL,
    "cliente_id" bigint NOT NULL
);

CREATE TABLE IF NOT EXISTS "gestion_detalle_pedido" (
    "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "cantidad" integer NOT NULL CHECK ("cantidad" >= 0),
    "precio_unitario" numeric(10, 2) NOT NULL,
    "material_id" integer NOT NULL,
    "pedido_id" bigint NOT NULL
);

ALTER TABLE "gestion_pedido"
    ADD CONSTRAINT "gestion_pedido_cliente_id_dc3de646_fk_usuario_id"
    FOREIGN KEY ("cliente_id") REFERENCES "usuario" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS "gestion_pedido_cliente_id_dc3de646" ON "gestion_pedido" ("cliente_id");

ALTER TABLE "gestion_detalle_pedido"
    ADD CONSTRAINT "gestion_detalle_pedi_material_id_044b16eb_fk_material_"
    FOREIGN KEY ("material_id") REFERENCES "material_construccion" ("cod_material") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "gestion_detalle_pedido"
    ADD CONSTRAINT "gestion_detalle_pedido_pedido_id_cc29ccfc_fk_gestion_pedido_id"
    FOREIGN KEY ("pedido_id") REFERENCES "gestion_pedido" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS "gestion_detalle_pedido_material_id_044b16eb" ON "gestion_detalle_pedido" ("material_id");
CREATE INDEX IF NOT EXISTS "gestion_detalle_pedido_pedido_id_cc29ccfc" ON "gestion_detalle_pedido" ("pedido_id");

CREATE TABLE IF NOT EXISTS "historial_reporte" (
    "codigo_historia" varchar(20) NOT NULL PRIMARY KEY,
    "fecha_reporte" timestamp with time zone NOT NULL,
    "descripcion" text NOT NULL
);
CREATE INDEX IF NOT EXISTS "historial_reporte_codigo_historia_6386e36c_like" ON "historial_reporte" ("codigo_historia" varchar_pattern_ops);

ALTER TABLE "reporte" ADD COLUMN IF NOT EXISTS "usuario_id" bigint NULL;
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'reporte_usuario_id_7d124763_fk_usuario_id'
    ) THEN
        ALTER TABLE "reporte" ADD CONSTRAINT "reporte_usuario_id_7d124763_fk_usuario_id"
            FOREIGN KEY ("usuario_id") REFERENCES "usuario"("id") DEFERRABLE INITIALLY DEFERRED;
    END IF;
END $$;
CREATE INDEX IF NOT EXISTS "reporte_usuario_id_7d124763" ON "reporte" ("usuario_id");

ALTER TABLE "historial_reporte" ADD COLUMN "reporte_id" varchar(20) NOT NULL
    CONSTRAINT "historial_reporte_reporte_id_d5d143cf_fk_reporte_numero_reporte"
    REFERENCES "reporte"("numero_reporte") DEFERRABLE INITIALLY DEFERRED;
SET CONSTRAINTS "historial_reporte_reporte_id_d5d143cf_fk_reporte_numero_reporte" IMMEDIATE;
CREATE INDEX IF NOT EXISTS "historial_reporte_reporte_id_d5d143cf" ON "historial_reporte" ("reporte_id");
CREATE INDEX IF NOT EXISTS "historial_reporte_reporte_id_d5d143cf_like" ON "historial_reporte" ("reporte_id" varchar_pattern_ops);

ALTER TABLE "historial_actividad" ADD COLUMN IF NOT EXISTS "usuario_id" bigint NULL;
ALTER TABLE "historial_actividad" ADD COLUMN IF NOT EXISTS "ip" inet NULL;
ALTER TABLE "historial_actividad" ADD COLUMN IF NOT EXISTS "registro_id" integer NULL;
ALTER TABLE "historial_actividad" ADD COLUMN IF NOT EXISTS "tabla" varchar(50) NULL;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_name = 'historial_actividad' AND column_name = 'fecha'
    ) THEN
        ALTER TABLE "historial_actividad" ADD COLUMN "fecha" timestamp with time zone NOT NULL DEFAULT now();
        ALTER TABLE "historial_actividad" ALTER COLUMN "fecha" DROP DEFAULT;
    END IF;
END $$;

ALTER TABLE "historial_actividad" ALTER COLUMN "descripcion" DROP NOT NULL;
ALTER TABLE "historial_actividad" ALTER COLUMN "fecha_hora" DROP NOT NULL;
ALTER TABLE "historial_actividad" ALTER COLUMN "modulo" DROP NOT NULL;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'historial_actividad_usuario_id_eb57c0a1_fk_usuario_id'
    ) THEN
        ALTER TABLE "historial_actividad" ADD CONSTRAINT "historial_actividad_usuario_id_eb57c0a1_fk_usuario_id"
            FOREIGN KEY ("usuario_id") REFERENCES "usuario"("id") DEFERRABLE INITIALLY DEFERRED;
    END IF;
END $$;
CREATE INDEX IF NOT EXISTS "historial_actividad_usuario_id_eb57c0a1" ON "historial_actividad" ("usuario_id");

DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM pg_tables WHERE schemaname='public' AND tablename='historial_actividad')
       AND NOT EXISTS (SELECT 1 FROM pg_tables WHERE schemaname='public' AND tablename='historial') THEN
        ALTER TABLE "historial_actividad" RENAME TO "historial";
    END IF;
END $$;

COMMIT;
