# Generated by Django 5.1.5 on 2026-05-14 22:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ordenes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id_factura', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('pagada', 'Pagada'), ('anulada', 'Anulada')], default='pendiente', max_length=15)),
                ('sincronizado', models.BooleanField(default=False)),
                ('pedido', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='factura', to='ordenes.pedido')),
            ],
            options={
                'db_table': 'factura',
                'ordering': ['-fecha'],
            },
        ),
    ]
