# Generated by Django 5.1.3 on 2025-01-01 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("usuarios", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CategoriaAyuda",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("nombre", models.CharField(max_length=100)),
                ("descripcion", models.TextField(blank=True)),
                ("orden", models.PositiveIntegerField(default=0)),
            ],
            options={
                "db_table": "categoria_ayuda",
                "verbose_name_plural": "Categorías de Ayuda",
                "ordering": ["orden", "nombre"],
            },
        ),
        migrations.CreateModel(
            name="ColorSistema",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("nombre", models.CharField(max_length=100)),
                ("codigo_hex", models.CharField(max_length=7)),
                ("descripcion", models.TextField(blank=True)),
                ("uso", models.CharField(max_length=200)),
                ("activo", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "color_sistema",
                "verbose_name": "Color del Sistema",
                "verbose_name_plural": "Colores del Sistema",
            },
        ),
        migrations.CreateModel(
            name="GuiaEdicion",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("titulo", models.CharField(max_length=200)),
                ("contenido", models.TextField()),
                ("orden", models.PositiveIntegerField(default=0)),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_actualizacion", models.DateTimeField(auto_now=True)),
                ("es_favorito", models.BooleanField(default=False)),
                ("activo", models.BooleanField(default=True)),
                ("categoria", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="guias", to="ayuda.categoriaayuda")),
            ],
            options={
                "db_table": "guia_edicion",
                "verbose_name": "Guía de Edición",
                "verbose_name_plural": "Guías de Edición",
                "ordering": ["categoria", "orden", "titulo"],
            },
        ),
        migrations.CreateModel(
            name="ManualUsuario",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("titulo", models.CharField(max_length=200)),
                ("version", models.CharField(max_length=50)),
                ("archivo", models.FileField(upload_to="manuales/")),
                ("fecha_publicacion", models.DateField(default=django.utils.timezone.now)),
                ("activo", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "manual_usuario",
                "verbose_name": "Manual de Usuario",
                "verbose_name_plural": "Manuales de Usuario",
            },
        ),
        migrations.CreateModel(
            name="PasoGuia",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("numero_paso", models.PositiveIntegerField()),
                ("titulo_paso", models.CharField(max_length=200)),
                ("descripcion", models.TextField()),
                ("imagen", models.ImageField(blank=True, null=True, upload_to="ayuda/pasos/")),
                ("url_referencia", models.URLField(blank=True, null=True)),
                ("guia", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="pasos", to="ayuda.guiaedicion")),
            ],
            options={
                "db_table": "paso_guia",
                "ordering": ["guia", "numero_paso"],
            },
        ),
        migrations.CreateModel(
            name="SugerenciaRecomendacion",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("tipo", models.CharField(choices=[("sugerencia", "Sugerencia"), ("recomendacion", "Recomendación"), ("bug", "Reporte de Error"), ("mejora", "Mejora")], max_length=20)),
                ("titulo", models.CharField(max_length=200)),
                ("descripcion", models.TextField()),
                ("estado", models.CharField(choices=[("nuevo", "Nuevo"), ("en_revision", "En Revisión"), ("implementado", "Implementado"), ("rechazado", "Rechazado")], default="nuevo", max_length=20)),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_actualizacion", models.DateTimeField(auto_now=True)),
                ("usuario", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="sugerencias", to="usuarios.usuario")),
            ],
            options={
                "db_table": "sugerencia_recomendacion",
                "ordering": ["-fecha_creacion"],
            },
        ),
    ]
