# Generated by Django 6.0.4 on 2026-04-13 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transporte', '0002_alter_entrega_conductor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrega',
            name='vehiculo',
            field=models.CharField(blank=True, default='', max_length=100),
            preserve_default=False,
        ),
    ]
