# Generated by Django 5.1.5 on 2026-05-14 22:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='perfil_cliente', serialize=False, to='usuarios.usuario')),
                ('direccion_principal', models.CharField(default='Por definir', max_length=200)),
                ('tipo_cliente', models.CharField(choices=[('persona', 'Persona Natural'), ('empresa', 'Empresa'), ('gobierno', 'Entidad Gubernamental')], default='persona', max_length=20)),
                ('nombre_empresa', models.CharField(blank=True, max_length=200, null=True)),
                ('nit', models.CharField(blank=True, max_length=20, null=True)),
                ('contacto_alternativo', models.CharField(blank=True, max_length=100, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'cliente',
            },
        ),
    ]
