# Generated by Django 6.0.4 on 2026-04-25 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_alter_cliente_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cliente',
            table='perfil_cliente',
        ),
    ]
