# Generated by Django 5.1.5 on 2026-08-11 15:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_alter_cliente_options_cliente_direccion_and_more'),
        ('facturacion', '0002_initial'),
        ('ordenes', '0005_entrega_conductor_usuario_pedido_catalogo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='cliente_usuario',
            field=models.ForeignKey(blank=True, db_column='cliente_usuario_id_legacy', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='facturas_usuario', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='factura',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='facturas', to='clientes.cliente'),
        ),
        migrations.AddConstraint(
            model_name='factura',
            constraint=models.CheckConstraint(condition=models.Q(('subtotal__gte', 0), ('subtotal__isnull', True), _connector='OR'), name='chk_factura_subtotal_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='factura',
            constraint=models.CheckConstraint(condition=models.Q(('iva__gte', 0), ('iva__isnull', True), _connector='OR'), name='chk_factura_iva_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='factura',
            constraint=models.CheckConstraint(condition=models.Q(('total__gte', 0), ('total__isnull', True), _connector='OR'), name='chk_factura_total_gte_0'),
        ),
    ]
