# Generated by Django 5.1.5 on 2026-08-25 00:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0003_factura_cliente_usuario_alter_factura_cliente_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='factura',
            options={'ordering': ['-fecha'], 'permissions': (('anular_factura', 'Puede anular facturas'), ('ver_facturas_todas', 'Puede ver todas las facturas'))},
        ),
    ]
