# Generated by Django 5.1.5 on 2026-09-09 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0002_normalize_factura_3fn'),
        ('facturacion', '0004_alter_factura_options'),
    ]

    operations = [
    ]
