# Generated by Django 5.1.5 on 2026-09-09 15:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0005_merge_20260909_0900'),
        ('ordenes', '0009_remove_pedido_chk_pedido_precio_gte_0_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='factura',
            name='chk_factura_subtotal_gte_0',
        ),
        migrations.RemoveConstraint(
            model_name='factura',
            name='chk_factura_iva_gte_0',
        ),
        migrations.RemoveConstraint(
            model_name='factura',
            name='chk_factura_total_gte_0',
        ),
        migrations.AlterField(
            model_name='factura',
            name='pedido',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='factura', to='ordenes.pedido'),
        ),
    ]
