# Generated by Django 5.1.5 on 2026-09-09 15:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_cliente_gasto_acumulado'),
        ('facturacion', '0006_remove_factura_chk_factura_subtotal_gte_0_and_more'),
        ('ordenes', '0009_remove_pedido_chk_pedido_precio_gte_0_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='factura',
            constraint=models.CheckConstraint(condition=models.Q(('subtotal__gte', 0), ('subtotal__isnull', True), _connector='OR'), name='chk_factura_subtotal_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='factura',
            constraint=models.CheckConstraint(condition=models.Q(('iva__gte', 0), ('iva__isnull', True), _connector='OR'), name='chk_factura_iva_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='factura',
            constraint=models.CheckConstraint(condition=models.Q(('total__gte', 0), ('total__isnull', True), _connector='OR'), name='chk_factura_total_gte_0'),
        ),
    ]
