# Generated by Django 5.1.5 on 2026-09-16 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0007_factura_chk_factura_subtotal_gte_0_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='factura',
            options={'ordering': ['-fecha'], 'permissions': (('ver_facturas_todas', 'Puede ver todas las facturas'),)},
        ),
    ]
