# Generated by Django 6.0.4 on 2026-04-08 19:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='material',
            options={'ordering': ['nombre'], 'verbose_name': 'Material', 'verbose_name_plural': 'Materiales'},
        ),
        migrations.AddField(
            model_name='material',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AddField(
            model_name='material',
            name='categoria',
            field=models.CharField(choices=[('cemento', 'Cemento'), ('acero', 'Acero'), ('madera', 'Madera'), ('pintura', 'Pintura'), ('herramienta', 'Herramienta'), ('otro', 'Otro')], default='otro', max_length=50, verbose_name='Categoría'),
        ),
        migrations.AddField(
            model_name='material',
            name='descripcion',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción'),
        ),
        migrations.AddField(
            model_name='material',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='material',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='material',
            name='unidad_medida',
            field=models.CharField(default='unidad', max_length=50, verbose_name='Unidad de medida'),
        ),
        migrations.AlterField(
            model_name='material',
            name='nombre',
            field=models.CharField(max_length=200, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='material',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio (COP)'),
        ),
        migrations.AlterField(
            model_name='material',
            name='stock',
            field=models.PositiveIntegerField(default=0, verbose_name='Stock disponible'),
        ),
    ]
