# Generated by Django 6.0.4 on 2026-04-25 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_alter_movimientoinventario_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='movimientoinventario',
            table='movimiento_inventario',
        ),
    ]
