# Generated by Django 6.0.4 on 2026-04-08 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_alter_material_options_material_activo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='material',
            name='unidad_medida',
        ),
        migrations.AddField(
            model_name='material',
            name='tipo',
            field=models.CharField(choices=[('Cemento', 'Cemento'), ('Arena', 'Arena'), ('Grava', 'Grava'), ('Ladrillo', 'Ladrillo'), ('Herramientas', 'Herramientas'), ('Otro', 'Otro')], default='Otro', max_length=50, verbose_name='Tipo'),
        ),
    ]
