# Generated by Django 5.1.5 on 2026-05-10 04:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0004_compra_usuario'),
        ('inventario', '0003_alter_movimientoinventario_table'),
        ('ordenes', '0006_alter_entrega_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movimientoinventario',
            name='motivo',
        ),
        migrations.RemoveField(
            model_name='movimientoinventario',
            name='referencia_id',
        ),
        migrations.AddField(
            model_name='movimientoinventario',
            name='compra',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos', to='compras.compra'),
        ),
        migrations.AddField(
            model_name='movimientoinventario',
            name='observacion',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='movimientoinventario',
            name='orden',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos', to='ordenes.orden'),
        ),
    ]
