# Generated by Django 5.1.5 on 2026-08-25 00:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ordenes', '0006_fix_db_column_duplicados'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Novedad',
            fields=[
                ('id_novedad', models.BigAutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('demora', 'Demora en entrega'), ('producto_danado', 'Producto dañado'), ('cantidad_incorrecta', 'Cantidad incorrecta'), ('devolucion', 'Devolución'), ('observacion', 'Observación')], max_length=30)),
                ('descripcion', models.TextField()),
                ('estado', models.CharField(choices=[('abierta', 'Abierta'), ('en_atencion', 'En atención'), ('cerrada', 'Cerrada'), ('rechazada', 'Rechazada')], default='abierta', max_length=15)),
                ('fecha_generada', models.DateTimeField(auto_now_add=True)),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='novedades', to='ordenes.pedido')),
                ('reportado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='novedades_reportadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'novedad',
                'ordering': ['-fecha_generada'],
                'permissions': (('registrar_novedad', 'Puede registrar novedades'),),
            },
        ),
        migrations.CreateModel(
            name='Seguimiento',
            fields=[
                ('id_seguimiento', models.BigAutoField(primary_key=True, serialize=False)),
                ('fecha_seguimiento', models.DateTimeField(auto_now_add=True)),
                ('comentario', models.TextField()),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('respondida', 'Respondida'), ('escalado', 'Escalado')], default='pendiente', max_length=15)),
                ('atendido_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seguimientos_atendidos', to=settings.AUTH_USER_MODEL)),
                ('novedad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seguimientos', to='novedades.novedad')),
            ],
            options={
                'db_table': 'seguimiento',
                'ordering': ['-fecha_seguimiento'],
                'permissions': (('responder_seguimiento', 'Puede responder seguimientos'),),
            },
        ),
        migrations.CreateModel(
            name='RespuestaSeguimiento',
            fields=[
                ('id_respuesta', models.BigAutoField(primary_key=True, serialize=False)),
                ('fecha_respuesta', models.DateTimeField(auto_now_add=True)),
                ('texto', models.TextField()),
                ('estado', models.CharField(choices=[('aceptada', 'Aceptada'), ('rechazada', 'Rechazada'), ('en_gestion', 'En gestión')], default='aceptada', max_length=15)),
                ('redactada_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='respuestas_redactadas', to=settings.AUTH_USER_MODEL)),
                ('seguimiento', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='respuesta', to='novedades.seguimiento')),
            ],
            options={
                'db_table': 'respuesta_seguimiento',
                'ordering': ['-fecha_respuesta'],
            },
        ),
        migrations.AddIndex(
            model_name='novedad',
            index=models.Index(fields=['estado'], name='novedad_estado_af8cac_idx'),
        ),
        migrations.AddIndex(
            model_name='novedad',
            index=models.Index(fields=['tipo'], name='novedad_tipo_10af70_idx'),
        ),
    ]
