# Generated by Django 5.1.5 on 2026-08-28 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novedades', '0001_initial'),
        ('ordenes', '0007_alter_entrega_options_alter_pedido_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='novedad',
            name='pedido',
        ),
        migrations.AddField(
            model_name='novedad',
            name='entrega',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='novedades', to='ordenes.entrega'),
            preserve_default=False,
        ),
    ]
