# Generated by Django 6.0.4 on 2026-04-25 02:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='compra',
            table='compras',
        ),
        migrations.AlterModelTable(
            name='detallecompra',
            table='detalles_compra',
        ),
    ]
