# Generated by Django 6.0.4 on 2026-04-18 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0001_initial'),
        ('usuarios', '0004_vehiculo_conductor_alter_vehiculo_estado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.proveedor', verbose_name='Proveedor'),
        ),
        migrations.DeleteModel(
            name='Proveedor',
        ),
    ]
