# Generated by Django 5.1.5 on 2026-06-12 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='observaciones',
            field=models.TextField(blank=True, default=''),
        ),
    ]
