# Generated by Django 6.0.4 on 2026-04-25 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0002_alter_compra_table_alter_detallecompra_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='compra',
            table='compra',
        ),
        migrations.AlterModelTable(
            name='detallecompra',
            table='detalle_compra',
        ),
    ]
