# Generated by Django 6.0.3 on 2026-03-06 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='confirmar_contrasena',
            field=models.CharField(default='123456', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='contrasena',
            field=models.CharField(default='default', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('admin', 'Administrador'), ('conductor', 'Conductor'), ('cliente', 'Cliente')], default='default', max_length=20),
            preserve_default=False,
        ),
    ]
