# Generated by Codex on 2026-07-09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usuarios", "0004_proveedor_categoria_proveedor_contacto_nombre_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="proveedor",
            name="activo",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="proveedor",
            name="ciudad",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="proveedor",
            name="fecha_registro",
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
