# Generated by Django 5.1.5 on 2026-07-23 14:03

import usuarios.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_proveedor_estado_perfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='foto_perfil',
            field=models.FileField(blank=True, null=True, upload_to=usuarios.models.foto_perfil_upload_path),
        ),
    ]
