# Generated by Django 5.1.5 on 2026-08-11 15:42

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_alter_usuario_foto_perfil'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id_rol', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_rol', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Rol',
                'verbose_name_plural': 'Roles',
                'db_table': 'rol',
            },
        ),
        migrations.CreateModel(
            name='UsuarioRol',
            fields=[
                ('id_usuario_rol', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_revocacion', models.DateTimeField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Usuario Rol',
                'verbose_name_plural': 'Usuario Roles',
                'db_table': 'usuario_rol',
            },
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='catalogo',
            field=models.ForeignKey(blank=True, db_column='codigo_catalogo', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehiculos', to='usuarios.catalogo'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='capacidad_carga',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
        migrations.AddConstraint(
            model_name='materialconstruccion',
            constraint=models.CheckConstraint(condition=models.Q(('precio_referencia__gte', 0)), name='chk_material_precio_referencia_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='stock',
            constraint=models.CheckConstraint(condition=models.Q(('cantidad_actual__gte', 0)), name='chk_stock_cantidad_actual_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='stock',
            constraint=models.CheckConstraint(condition=models.Q(('stock_minimo__gte', 0)), name='chk_stock_minimo_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='vehiculo',
            constraint=models.CheckConstraint(condition=models.Q(('capacidad_carga__gt', 0)), name='chk_vehiculo_capacidad_carga_gt_0'),
        ),
        migrations.AddField(
            model_name='usuariorol',
            name='rol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarios', to='usuarios.rol'),
        ),
        migrations.AddField(
            model_name='usuariorol',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario_roles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='usuariorol',
            unique_together={('usuario', 'rol')},
        ),
    ]
