# Generated by Django 5.1.5 on 2026-08-25 00:46

import django.contrib.auth.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('usuarios', '0008_add_unique_tipo_documento_documento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permiso',
            fields=[
                ('id_permiso', models.BigAutoField(primary_key=True, serialize=False)),
                ('codename', models.CharField(max_length=100, unique=True)),
                ('nombre', models.CharField(max_length=150)),
                ('funcion', models.CharField(choices=[('aprobar_pedido', 'Aprobar pedido'), ('asignar_vehiculo', 'Asignar vehículo'), ('registrar_novedad', 'Registrar novedad'), ('responder_seguimiento', 'Responder seguimiento'), ('anular_factura', 'Anular factura'), ('registrar_pago', 'Registrar pago'), ('autorizar_despacho', 'Autorizar despacho'), ('gestionar_inventario', 'Gestionar inventario'), ('gestionar_proveedor', 'Gestionar proveedor'), ('ver_bitacora', 'Ver bitácora')], max_length=60)),
            ],
            options={
                'verbose_name': 'Permiso',
                'verbose_name_plural': 'Permisos',
                'db_table': 'permiso',
                'ordering': ['funcion', 'codename'],
            },
        ),
        migrations.CreateModel(
            name='RolProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Rol de seguridad',
                'verbose_name_plural': 'Roles de seguridad',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('auth.group',),
            managers=[
                ('objects', django.contrib.auth.models.GroupManager()),
            ],
        ),
        migrations.AlterModelOptions(
            name='materialconstruccion',
            options={'permissions': (('gestionar_inventario', 'Puede gestionar inventario'),), 'verbose_name': 'Material de Construcción', 'verbose_name_plural': 'Materiales de Construcción'},
        ),
        migrations.CreateModel(
            name='PermisoUsuario',
            fields=[
                ('id_permiso_usuario', models.BigAutoField(primary_key=True, serialize=False)),
                ('fecha_otorgado', models.DateTimeField(auto_now_add=True)),
                ('vigente_hasta', models.DateTimeField(blank=True, null=True)),
                ('permiso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarios_directos', to='usuarios.permiso')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permisos_directos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'permiso_usuario',
                'unique_together': {('usuario', 'permiso')},
            },
        ),
        migrations.CreateModel(
            name='RolPermiso',
            fields=[
                ('id_rol_permiso', models.BigAutoField(primary_key=True, serialize=False)),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True)),
                ('permiso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles_negocio', to='usuarios.permiso')),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permisos_negocio', to='usuarios.rol')),
            ],
            options={
                'db_table': 'rol_permiso_negocio',
                'unique_together': {('rol', 'permiso')},
            },
        ),
        migrations.CreateModel(
            name='UsuarioRolNegocio',
            fields=[
                ('id_usuario_rol', models.BigAutoField(primary_key=True, serialize=False)),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_revocacion', models.DateTimeField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarios_negocio', to='usuarios.rol')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles_negocio', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'usuario_rol_negocio',
                'unique_together': {('usuario', 'rol')},
            },
        ),
    ]
