# Generated by Django 5.1.5 on 2026-09-09 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0008_catalogo_required_and_names_consolidation'),
        ('usuarios', '0009_permiso_rolproxy_alter_materialconstruccion_options_and_more'),
    ]

    operations = [
    ]
