# Generated by Django 5.1.5 on 2026-09-09 15:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0010_merge_20260909_0900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialconstruccion',
            name='catalogo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materiales', to='usuarios.catalogo'),
        ),
    ]
