# Generated by Django 5.2.8 on 2026-10-05 15:26

import apps.pagos.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0003_cliente_gasto_acumulado'),
        ('pedidos', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(editable=False, max_length=20, unique=True)),
                ('fecha_emision', models.DateTimeField(default=django.utils.timezone.now)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('impuestos', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('estado', models.CharField(choices=[('emitida', 'Emitida'), ('parcial', 'Pago parcial'), ('pagada', 'Pagada'), ('vencida', 'Vencida'), ('anulada', 'Anulada')], default='emitida', max_length=10)),
                ('uuid_publico', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='facturas', to='clientes.cliente')),
                ('pedido', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='factura', to='pedidos.pedido')),
            ],
            options={
                'db_table': 'factura',
                'ordering': ['-fecha_emision'],
                'permissions': (('ver_facturacion', 'Puede ver el módulo de facturación'), ('emitir_factura', 'Puede emitir facturas'), ('registrar_pago_admin', 'Puede registrar un pago en nombre del cliente')),
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metodo', models.CharField(choices=[('nequi', 'Nequi'), ('daviplata', 'DaviPlata'), ('bancolombia', 'Bancolombia'), ('contraentrega', 'Contraentrega')], db_column='codigo_metodo_pago', max_length=20)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('comprobante', models.FileField(blank=True, db_column='comprobante', null=True, upload_to=apps.pagos.models.comprobante_upload_to)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado')], db_column='estado_pago', default='pendiente', max_length=20)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, db_column='fecha_creacion')),
                ('fecha_revision', models.DateTimeField(blank=True, db_column='fecha_actualizacion', null=True)),
                ('observaciones', models.TextField(blank=True, db_column='motivo_rechazo')),
                ('pedido', models.OneToOneField(db_column='pedido_id', on_delete=django.db.models.deletion.CASCADE, related_name='pago', to='pedidos.pedido')),
                ('revisado_por', models.ForeignKey(blank=True, db_column='revisado_por_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos_revisados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pago_pedido',
                'ordering': ['-fecha_registro'],
                'permissions': (('revisar_pago', 'Puede revisar y aprobar o rechazar pagos'), ('registrar_pago', 'Puede registrar un pago')),
            },
        ),
        migrations.CreateModel(
            name='DetallePago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concepto', models.CharField(db_column='concepto', max_length=200)),
                ('monto', models.DecimalField(db_column='monto', decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('pago', models.ForeignKey(db_column='pago_id', on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='pagos.pago')),
            ],
            options={
                'db_table': 'detalle_pago',
            },
        ),
        migrations.CreateModel(
            name='PagoFactura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('metodo', models.CharField(choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia'), ('tarjeta', 'Tarjeta'), ('pse', 'PSE')], max_length=20)),
                ('referencia', models.CharField(blank=True, max_length=100)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=10)),
                ('fecha_registro', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_revision', models.DateTimeField(blank=True, null=True)),
                ('evidencia', models.ImageField(blank=True, help_text='Evidencia fotográfica del comprobante', null=True, upload_to=apps.pagos.models._evidencia_upload_to)),
                ('observaciones', models.TextField(blank=True)),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos_factura', to='pagos.factura')),
                ('registrado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('revisado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pago_factura',
                'ordering': ['-fecha_registro'],
            },
        ),
        migrations.AddConstraint(
            model_name='pago',
            constraint=models.CheckConstraint(condition=models.Q(('monto__gte', 0)), name='chk_pago_monto_gte_0'),
        ),
    ]
