# Generated by Django 5.1.5 on 2026-06-01 13:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('facturacion', '0002_initial'),
        ('pagos', '0001_initial'),
        ('usuarios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='codigo_metodo_pago',
            field=models.ForeignKey(db_column='codigo_metodo_pago', on_delete=django.db.models.deletion.PROTECT, to='usuarios.metodopago'),
        ),
        migrations.AddField(
            model_name='pago',
            name='factura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='facturacion.factura'),
        ),
        migrations.AddField(
            model_name='pago',
            name='registrado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
