# Generated by Django 6.0.4 on 2026-04-25 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0002_alter_pago_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='pago',
            table='pago',
        ),
    ]
