# Generated by Django 5.1.5 on 2026-08-14 03:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BloqueoIP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(db_index=True, verbose_name='Dirección IP')),
                ('tipo', models.CharField(choices=[('unauthorized_access', 'Acceso no autorizado repetido'), ('brute_force', 'Fuerza bruta (intentos login)'), ('tampering', 'Manipulación de licencia/sistema'), ('manual', 'Bloqueo manual por administrador')], default='unauthorized_access', max_length=32)),
                ('motivo', models.TextField(blank=True, default='')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('expira_en', models.DateTimeField(blank=True, help_text='Si es nulo, el bloqueo es permanente.', null=True)),
                ('activo', models.BooleanField(db_index=True, default=True)),
                ('intentos_asociados', models.PositiveIntegerField(default=0)),
                ('bloqueado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'bloqueo_ip',
                'ordering': ['-creado_en'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('activo', True)), fields=('ip', 'activo'), name='uq_bloqueo_ip_activo')],
            },
        ),
        migrations.CreateModel(
            name='SecurityEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('unauthorized_access', 'Acceso no autorizado'), ('role_violation', 'Intento de salto de rol'), ('license_tamper', 'Manipulación de licencia'), ('ip_blocked', 'IP bloqueada'), ('login_failed', 'Login fallido'), ('login_ok', 'Login exitoso'), ('admin_switch', 'Superadmin cambió de panel'), ('security_warning', 'Advertencia de seguridad')], db_index=True, max_length=40)),
                ('gravedad', models.CharField(choices=[('info', 'Informativo'), ('warning', 'Advertencia'), ('high', 'Alta'), ('critical', 'Crítica')], default='warning', max_length=10)),
                ('ip', models.GenericIPAddressField(blank=True, db_index=True, null=True)),
                ('username_str', models.CharField(blank=True, db_index=True, default='', max_length=150)),
                ('path', models.CharField(blank=True, default='', max_length=512)),
                ('metodo_http', models.CharField(blank=True, default='', max_length=10)),
                ('user_agent', models.CharField(blank=True, default='', max_length=512)),
                ('referer', models.CharField(blank=True, default='', max_length=512)),
                ('detalles', models.JSONField(blank=True, default=dict, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('advertencia_mostrada', models.BooleanField(default=False)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_seguridad', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'security_event',
                'ordering': ['-creado_en'],
                'indexes': [models.Index(fields=['ip', 'creado_en'], name='security_ev_ip_f8a68e_idx'), models.Index(fields=['tipo', 'creado_en'], name='security_ev_tipo_0694be_idx')],
            },
        ),
    ]
