BEGIN;

-- =========================================================
-- 1) compra.proveedor_id -> compra.codigo_proveedor
--    (confirmado como rename: proveedor_id existe en la BD remota)
-- =========================================================
DO $$
BEGIN
    IF EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_name = 'compra' AND column_name = 'proveedor_id'
    ) AND NOT EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_name = 'compra' AND column_name = 'codigo_proveedor'
    ) THEN
        ALTER TABLE "compra" RENAME COLUMN "proveedor_id" TO "codigo_proveedor";
    END IF;
END $$;

-- =========================================================
-- 2) detalle_compra.compra_id -> detalle_compra.id_compra
--    (confirmado como rename: compra_id existe en la BD remota)
-- =========================================================
DO $$
BEGIN
    IF EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_name = 'detalle_compra' AND column_name = 'compra_id'
    ) AND NOT EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_name = 'detalle_compra' AND column_name = 'id_compra'
    ) THEN
        ALTER TABLE "detalle_compra" RENAME COLUMN "compra_id" TO "id_compra";
    END IF;
END $$;

-- =========================================================
-- 3) detalle_compra.material_id -> detalle_compra.cod_material
--    (confirmado como rename: material_id existe en la BD remota)
-- =========================================================
DO $$
BEGIN
    IF EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_name = 'detalle_compra' AND column_name = 'material_id'
    ) AND NOT EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_name = 'detalle_compra' AND column_name = 'cod_material'
    ) THEN
        ALTER TABLE "detalle_compra" RENAME COLUMN "material_id" TO "cod_material";
    END IF;
END $$;

-- =========================================================
-- 4) vehiculo.codigo_catalogo  -- SIN CONFIRMAR: puede ser rename o columna nueva
--    Este bloque solo CREA la columna si no existe ninguna variante de ella.
--    Si al verificar descubres que existe p.ej. "catalogo_id", cambia este
--    bloque por un RENAME COLUMN como los anteriores, en vez de correrlo tal cual.
-- =========================================================
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_name = 'vehiculo' AND column_name = 'codigo_catalogo'
    ) THEN
        ALTER TABLE "vehiculo" ADD COLUMN "codigo_catalogo" varchar(20) NULL;
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conname = 'vehiculo_codigo_catalogo_1bbc66fb_fk_catalogo_codigo_catalogo'
    ) THEN
        ALTER TABLE "vehiculo"
            ADD CONSTRAINT "vehiculo_codigo_catalogo_1bbc66fb_fk_catalogo_codigo_catalogo"
            FOREIGN KEY ("codigo_catalogo") REFERENCES "catalogo" ("codigo_catalogo")
            DEFERRABLE INITIALLY DEFERRED;
    END IF;
END $$;

CREATE INDEX IF NOT EXISTS "vehiculo_codigo_catalogo_1bbc66fb" ON "vehiculo" ("codigo_catalogo");
CREATE INDEX IF NOT EXISTS "vehiculo_codigo_catalogo_1bbc66fb_like" ON "vehiculo" ("codigo_catalogo" varchar_pattern_ops);

-- =========================================================
-- 5) Constraints y tablas nuevas que el sqlmigrate original también generaba
--    (idempotentes, no dependen de si hubo rename o no)
-- =========================================================
CREATE TABLE IF NOT EXISTS "rol" (
    "id_rol" integer NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "nombre_rol" varchar(50) NOT NULL UNIQUE,
    "descripcion" text NULL,
    "activo" boolean NOT NULL
);
CREATE INDEX IF NOT EXISTS "rol_nombre_rol_77fbfff8_like" ON "rol" ("nombre_rol" varchar_pattern_ops);

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'chk_material_precio_referencia_gte_0'
    ) THEN
        ALTER TABLE "material_construccion"
            ADD CONSTRAINT "chk_material_precio_referencia_gte_0" CHECK ("precio_referencia" >= 0);
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'chk_stock_cantidad_actual_gte_0'
    ) THEN
        ALTER TABLE "stock"
            ADD CONSTRAINT "chk_stock_cantidad_actual_gte_0" CHECK ("cantidad_actual" >= 0);
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'chk_stock_minimo_gte_0'
    ) THEN
        ALTER TABLE "stock"
            ADD CONSTRAINT "chk_stock_minimo_gte_0" CHECK ("stock_minimo" >= 0);
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'chk_vehiculo_capacidad_carga_gt_0'
    ) THEN
        ALTER TABLE "vehiculo"
            ADD CONSTRAINT "chk_vehiculo_capacidad_carga_gt_0" CHECK ("capacidad_carga" > 0);
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'chk_compra_total_compra_gte_0'
    ) THEN
        ALTER TABLE "compra"
            ADD CONSTRAINT "chk_compra_total_compra_gte_0" CHECK ("total_compra" >= 0);
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'chk_detalle_compra_cantidad_gt_0'
    ) THEN
        ALTER TABLE "detalle_compra"
            ADD CONSTRAINT "chk_detalle_compra_cantidad_gt_0" CHECK ("cantidad" > 0);
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'chk_detalle_compra_precio_unitario_gte_0'
    ) THEN
        ALTER TABLE "detalle_compra"
            ADD CONSTRAINT "chk_detalle_compra_precio_unitario_gte_0" CHECK ("precio_unitario" >= 0);
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'uq_detalle_compra_compra_material'
    ) THEN
        ALTER TABLE "detalle_compra"
            ADD CONSTRAINT "uq_detalle_compra_compra_material" UNIQUE ("id_compra", "cod_material");
    END IF;
END $$;

COMMIT;
