# Generated by Django 5.1.5 on 2026-08-25 00:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('licensing', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Licencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=40, unique=True)),
                ('nombre', models.CharField(max_length=120)),
                ('descripcion', models.TextField(blank=True, default='')),
                ('fecha_emision', models.DateTimeField()),
                ('fecha_expiracion', models.DateTimeField()),
                ('estado', models.CharField(choices=[('activa', 'Activa'), ('expirada', 'Expirada'), ('revocada', 'Revocada')], default='activa', max_length=15)),
                ('archivo_cifrado_nonce', models.BinaryField()),
                ('archivo_cifrado_ciphertext', models.BinaryField()),
                ('archivo_cifrado_aad', models.BinaryField(default=b'constru-trans-lic-v1')),
                ('password_hash', models.CharField(max_length=128)),
                ('password_salt', models.BinaryField()),
                ('password_kdf_params', models.JSONField(default=dict)),
                ('rotaciones_password', models.PositiveIntegerField(default=0)),
                ('ultima_rotacion_password', models.DateTimeField(blank=True, null=True)),
                ('revocada_en', models.DateTimeField(blank=True, null=True)),
                ('motivo_revocacion', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('permisos', models.ManyToManyField(blank=True, help_text='Permisos Django (app.codename) que entrega esta licencia.', related_name='licencias', to='auth.permission')),
                ('revocada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='licencias_revocadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'licencia',
            },
        ),
        migrations.CreateModel(
            name='AuditoriaLicencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(choices=[('LICENCIA_CREADA', 'Licencia creada'), ('LICENCIA_ASIGNADA', 'Licencia asignada'), ('LICENCIA_DESASIGNADA', 'Licencia desasignada'), ('LICENCIA_REVOCADA', 'Licencia revocada'), ('LICENCIA_RENOVADA', 'Licencia renovada'), ('PASSWORD_ROTADO', 'Password del archivo rotado'), ('PERMISO_DENEGADO', 'Acceso denegado por permiso'), ('INTENTO_SWITCH_ROLE', 'Intento de cambio libre de rol')], max_length=30)),
                ('detalle', models.TextField(blank=True, default='')),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, default='', max_length=255)),
                ('exitosa', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cambios_licencia_realizados', to=settings.AUTH_USER_MODEL)),
                ('usuario_afectado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_licencia', to=settings.AUTH_USER_MODEL)),
                ('licencia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auditoria', to='licensing.licencia')),
            ],
            options={
                'db_table': 'licencia_auditoria',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UsuarioLicencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_desasignacion', models.DateTimeField(blank=True, null=True)),
                ('motivo_desasignacion', models.TextField(blank=True, default='')),
                ('ip_asignacion', models.GenericIPAddressField(blank=True, null=True)),
                ('asignada_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='licencias_asignadas_por', to=settings.AUTH_USER_MODEL)),
                ('licencia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asignaciones', to='licensing.licencia')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='licencias', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'usuario_licencia',
            },
        ),
        migrations.AddIndex(
            model_name='licencia',
            index=models.Index(fields=['estado', 'fecha_expiracion'], name='licencia_estado_287fc3_idx'),
        ),
        migrations.AddConstraint(
            model_name='usuariolicencia',
            constraint=models.UniqueConstraint(condition=models.Q(('fecha_desasignacion__isnull', True)), fields=('usuario', 'licencia'), name='uq_usuario_licencia_vigente'),
        ),
    ]
