# Generated by Django 5.1.5 on 2026-06-09 15:26

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Installation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("instance_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("customer_id", models.CharField(blank=True, default="", max_length=64)),
                ("activated_at", models.DateTimeField(blank=True, null=True)),
                ("last_validated_at", models.DateTimeField(blank=True, null=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("license_token", models.TextField(blank=True, default="")),
                ("build_hash", models.CharField(blank=True, default="", max_length=64)),
                ("manifest_hash", models.CharField(blank=True, default="", max_length=64)),
                ("status", models.CharField(default="pending", max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "licensing_installation",
            },
        ),
    ]
