# Generated by Django 6.0.4 on 2026-04-24 02:15

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100000000)])),
                ('sincronizado', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_empresa', models.CharField(max_length=150)),
                ('nit', models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_numeric_space', message='Solo se admiten números y espacios.', regex='^[0-9\\s]*$')])),
                ('contacto_nombre', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(code='invalid_numeric_space', message='Solo se admiten números y espacios.', regex='^[0-9\\s]*$')])),
                ('email', models.EmailField(max_length=254)),
                ('direccion', models.CharField(max_length=255)),
                ('categoria', models.CharField(help_text='Ej: Materiales de Construcción, Repuestos, etc.', max_length=100)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('sincronizado', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Proveedores',
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100000)])),
                ('ubicacion', models.CharField(default='Bodega Principal', max_length=100)),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True)),
                ('material', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stock_info', to='usuarios.material')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('admin', 'Administrador'), ('conductor', 'Conductor'), ('cliente', 'Cliente'), ('empleado', 'Empleado')], max_length=20)),
                ('nombres', models.CharField(default='', max_length=100)),
                ('apellidos', models.CharField(default='', max_length=100)),
                ('telefono', models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator(code='invalid_numeric_space', message='Solo se admiten números y espacios.', regex='^[0-9\\s]*$')])),
                ('foto_perfil', models.ImageField(blank=True, null=True, upload_to='perfiles/')),
                ('tipo_documento', models.CharField(choices=[('CC', 'Cédula de Ciudadanía'), ('CE', 'Cédula de Extranjería'), ('PA', 'Pasaporte'), ('PEP', 'Permiso Especial de Permanencia'), ('PPT', 'Permiso por Protección Temporal'), ('NIT', 'Número de Identificación Tributaria')], max_length=5)),
                ('documento', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(code='invalid_numeric_space', message='Solo se admiten números y espacios.', regex='^[0-9\\s]*$')])),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo'), ('suspendido', 'Suspendido')], default='activo', max_length=15)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='usuario', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(default='Nueva notificación', max_length=100)),
                ('mensaje', models.TextField()),
                ('tipo', models.CharField(choices=[('info', 'Información'), ('success', 'Éxito'), ('warning', 'Advertencia'), ('danger', 'Error')], default='info', max_length=10)),
                ('leida', models.BooleanField(default=False)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('link', models.CharField(blank=True, max_length=255, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to='usuarios.usuario')),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Administrador',
            fields=[
            ],
            options={
                'verbose_name': 'Administrador',
                'verbose_name_plural': 'Administradores',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('usuarios.usuario',),
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('usuarios.usuario',),
        ),
        migrations.CreateModel(
            name='Conductor',
            fields=[
            ],
            options={
                'verbose_name': 'Conductor',
                'verbose_name_plural': 'Conductores',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('usuarios.usuario',),
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=10, unique=True)),
                ('tipo', models.CharField(max_length=50)),
                ('capacidad', models.CharField(max_length=50)),
                ('estado', models.CharField(choices=[('disponible', 'Disponible'), ('en_ruta', 'En Ruta'), ('mantenimiento', 'Mantenimiento')], default='disponible', max_length=20)),
                ('sincronizado', models.BooleanField(default=False, help_text='Indica si el registro está sincronizado con la nube')),
                ('conductor', models.OneToOneField(blank=True, limit_choices_to={'rol': 'conductor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehiculo_asignado', to='usuarios.usuario')),
            ],
        ),
    ]
