# Generated by Django 5.1.5 on 2026-05-23 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='ubicacion',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
    ]
