# Generated by Django 5.1.5 on 2026-06-12 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacion',
            name='link',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
