# Generated by Django 6.0.4 on 2026-04-14 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='material',
            old_name='stock',
            new_name='stock_actual',
        ),
    ]
