# Generated by Django 6.0.4 on 2026-04-25 02:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_usuario_sincronizado'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='material',
            table='materiales',
        ),
        migrations.AlterModelTable(
            name='notificacion',
            table='notificaciones',
        ),
        migrations.AlterModelTable(
            name='proveedor',
            table='proveedores',
        ),
        migrations.AlterModelTable(
            name='stock',
            table='inventario_stock',
        ),
        migrations.AlterModelTable(
            name='usuario',
            table='usuarios',
        ),
        migrations.AlterModelTable(
            name='vehiculo',
            table='vehiculos',
        ),
    ]
