# Generated by Django 6.0.4 on 2026-04-14 02:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_rename_stock_material_stock_actual'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='documento',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Este campo solo debe contener números.', regex='^\\d+$')]),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator(message='Este campo solo debe contener números.', regex='^\\d+$')]),
        ),
    ]
