# Generated by Django 6.0.4 on 2026-04-14 03:42

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_material_activo_alter_usuario_documento_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='stock_actual',
        ),
        migrations.CreateModel(
            name='StockMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_actual', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('cantidad_minima', models.IntegerField(default=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('ubicacion', models.CharField(default='Bodega Principal', max_length=100)),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True)),
                ('material', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stock', to='usuarios.material')),
            ],
            options={
                'verbose_name': 'Stock de Material',
                'verbose_name_plural': 'Stocks de Materiales',
            },
        ),
    ]
