# Generated by Django 6.0.4 on 2026-04-25 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_alter_material_table_alter_notificacion_table_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='sincronizado',
            field=models.BooleanField(default=False, verbose_name='Sincronizado con Nube'),
        ),
    ]
