# Generated by Django 6.0.4 on 2026-04-25 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_alter_usuario_sincronizado'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='material',
            table='material',
        ),
        migrations.AlterModelTable(
            name='notificacion',
            table='notificacion',
        ),
        migrations.AlterModelTable(
            name='proveedor',
            table='proveedor',
        ),
        migrations.AlterModelTable(
            name='stock',
            table='stock',
        ),
        migrations.AlterModelTable(
            name='usuario',
            table='usuario',
        ),
        migrations.AlterModelTable(
            name='vehiculo',
            table='vehiculo',
        ),
    ]
