# Generated by Django 6.0.4 on 2026-04-26 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_alter_material_table_alter_notificacion_table_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculo',
            name='tipo_adquisicion',
            field=models.CharField(choices=[('propio', 'Propio (Comprado)'), ('alquilado', 'Alquilado')], default='propio', max_length=20, verbose_name='Tipo de Adquisición'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='estado',
            field=models.CharField(choices=[('disponible', 'Disponible'), ('en_ruta', 'En Ruta'), ('mantenimiento', 'Mantenimiento'), ('alquilado', 'Alquilado'), ('comprado', 'Comprado'), ('desactivado', 'Desactivado')], default='disponible', max_length=20),
        ),
    ]
