# Generated by Django 5.1.5 on 2026-05-09 21:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_vehiculo_tipo_adquisicion_alter_vehiculo_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilConductor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_licencia', models.CharField(max_length=50, unique=True)),
                ('categoria_licencia', models.CharField(max_length=10)),
                ('fecha_vencimiento_licencia', models.DateField()),
                ('codigo_eps', models.CharField(blank=True, max_length=50, null=True)),
                ('nombre_eps', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_conductor', to='usuarios.usuario')),
            ],
            options={
                'db_table': 'perfil_conductor',
            },
        ),
    ]
