# Generated by Django 6.0.4 on 2026-04-29 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_vehiculo_tipo_adquisicion_alter_vehiculo_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
