# Generated by Django 5.1.5 on 2026-05-10 03:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_perfilconductor'),
    ]

    operations = [
    ]
