# Generated by Django 5.1.5 on 2026-05-10 04:44

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0008_auto_20260509_2202'),
    ]

    operations = [
        migrations.CreateModel(
            name='Catalogo',
            fields=[
                ('codigo_catalogo', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nombre_empresa', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'catalogo',
            },
        ),
        migrations.CreateModel(
            name='EPS',
            fields=[
                ('codigo_eps', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nombre_eps', models.CharField(max_length=100)),
                ('ciudad', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=200)),
                ('telefono', models.CharField(max_length=20)),
                ('correo', models.EmailField(max_length=254)),
            ],
            options={
                'verbose_name_plural': 'EPS',
                'db_table': 'eps',
            },
        ),
        migrations.RenameField(
            model_name='material',
            old_name='precio',
            new_name='precio_referencia',
        ),
        migrations.RemoveField(
            model_name='perfilconductor',
            name='codigo_eps',
        ),
        migrations.RemoveField(
            model_name='perfilconductor',
            name='nombre_eps',
        ),
        migrations.AddField(
            model_name='material',
            name='color',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='material',
            name='marca',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='material',
            name='unidad_medida',
            field=models.CharField(default='unidad', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='perfilconductor',
            name='fecha_ingreso',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='perfilconductor',
            name='telefono_empresa',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='perfilconductor',
            name='tipo_licencia',
            field=models.CharField(default='A1', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stock',
            name='stock_minimo',
            field=models.IntegerField(default=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='capacidad_carga',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='fecha_registro',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='marca',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='modelo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='tipo_vehiculo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='capacidad',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='tipo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='material',
            name='catalogo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materiales', to='usuarios.catalogo'),
        ),
        migrations.CreateModel(
            name='ConductorVehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('conductor', models.ForeignKey(limit_choices_to={'rol': 'conductor'}, on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones_vehiculo', to='usuarios.usuario')),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones_conductor', to='usuarios.vehiculo')),
            ],
            options={
                'db_table': 'conductor_vehiculo',
                'ordering': ['-fecha_asignacion'],
            },
        ),
        migrations.AddField(
            model_name='perfilconductor',
            name='eps',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.eps'),
        ),
    ]
