# Generated by Django 5.2.8 on 2026-09-24 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0013_alter_usuario_managers'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MetodoPago',
        ),
    ]
