# Generated by Django 5.2.8 on 2026-09-24 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0008_proveedor_alter_detallecompra_material_and_more'),
        ('usuarios', '0014_delete_metodopago'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materialconstruccion',
            name='catalogo',
        ),
        migrations.RemoveField(
            model_name='vehiculo',
            name='catalogo',
        ),
        migrations.AlterUniqueTogether(
            name='conductorvehiculo',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='conductorvehiculo',
            name='conductor',
        ),
        migrations.RemoveField(
            model_name='conductorvehiculo',
            name='vehiculo',
        ),
        migrations.RemoveField(
            model_name='historialpreciomaterial',
            name='material',
        ),
        migrations.RemoveField(
            model_name='historialpreciomaterial',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='materialconstruccion',
            name='marca',
        ),
        migrations.RemoveField(
            model_name='materialconstruccion',
            name='unidad_medida',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='material',
        ),
        migrations.DeleteModel(
            name='Proveedor',
        ),
        migrations.DeleteModel(
            name='Catalogo',
        ),
        migrations.DeleteModel(
            name='ConductorVehiculo',
        ),
        migrations.DeleteModel(
            name='Vehiculo',
        ),
        migrations.DeleteModel(
            name='HistorialPrecioMaterial',
        ),
        migrations.DeleteModel(
            name='Marca',
        ),
        migrations.DeleteModel(
            name='UnidadMedida',
        ),
        migrations.DeleteModel(
            name='MaterialConstruccion',
        ),
        migrations.DeleteModel(
            name='Stock',
        ),
    ]
