# Generated by Django 5.1.5 on 2026-08-14 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_alter_cliente_options_cliente_direccion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='gasto_acumulado',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Gasto acumulado'),
        ),
    ]
