# Generated by Django 5.1.5 on 2026-05-10 04:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0009_catalogo_eps_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_reporte', models.CharField(max_length=20, unique=True)),
                ('tipo', models.CharField(choices=[('inventario', 'Inventario'), ('ventas', 'Ventas'), ('compras', 'Compras'), ('entregas', 'Entregas'), ('financiero', 'Financiero')], max_length=20)),
                ('fecha_generada', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('generado', 'Generado'), ('archivado', 'Archivado'), ('eliminado', 'Eliminado')], default='generado', max_length=15)),
                ('descripcion', models.TextField(blank=True)),
                ('archivo_pdf', models.FileField(blank=True, null=True, upload_to='reportes/')),
                ('generado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.usuario')),
            ],
            options={
                'db_table': 'reporte',
                'ordering': ['-fecha_generada'],
            },
        ),
        migrations.CreateModel(
            name='HistorialReporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_historia', models.CharField(max_length=20, unique=True)),
                ('fecha_reporte', models.DateTimeField(auto_now_add=True)),
                ('descripcion', models.TextField()),
                ('reporte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='reportes.reporte')),
            ],
            options={
                'db_table': 'historial_reporte',
                'ordering': ['-fecha_reporte'],
            },
        ),
    ]
