# Generated by Django 5.1.5 on 2026-06-09 15:26

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="HistorialReporte",
            fields=[
                (
                    "codigo_historia",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("fecha_reporte", models.DateTimeField(auto_now_add=True)),
                ("descripcion", models.TextField()),
            ],
            options={
                "db_table": "historial_reporte",
                "ordering": ["-fecha_reporte"],
            },
        ),
        migrations.CreateModel(
            name="Reporte",
            fields=[
                (
                    "numero_reporte",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("inventario", "Inventario"),
                            ("ventas", "Ventas"),
                            ("compras", "Compras"),
                            ("entregas", "Entregas"),
                            ("financiero", "Financiero"),
                        ],
                        max_length=20,
                    ),
                ),
                ("fecha_generada", models.DateTimeField(auto_now_add=True)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("generado", "Generado"),
                            ("archivado", "Archivado"),
                            ("eliminado", "Eliminado"),
                        ],
                        default="generado",
                        max_length=15,
                    ),
                ),
                ("descripcion", models.TextField(blank=True)),
                ("archivo_pdf", models.FileField(blank=True, null=True, upload_to="reportes/")),
            ],
            options={
                "db_table": "reporte",
                "ordering": ["-fecha_generada"],
            },
        ),
    ]
