# Generated by Django 6.0.6 on 2026-06-21 18:39

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0002_alter_vehiculo_estado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('cancelado', 'Cancelado'), ('en_camino', 'En camino'), ('entregado', 'Entregado')], default='pendiente', help_text='Estado del ciclo de vida del pedido.', max_length=12)),
                ('descuento', models.DecimalField(decimal_places=2, default=0, help_text='Descuento global aplicado al total bruto.', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('total', models.DecimalField(decimal_places=2, default=0, editable=False, help_text='Total neto después de aplicar descuento.', max_digits=12)),
                ('cliente', models.ForeignKey(help_text='Cliente que crea el pedido.', on_delete=django.db.models.deletion.PROTECT, related_name='pedidos_gestion', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Solicitud de Pedido',
                'verbose_name_plural': 'Solicitudes de Pedido',
                'db_table': 'gestion_pedido',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='DetalleSolicitudPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(help_text='Cantidad solicitada.', validators=[django.core.validators.MinValueValidator(1)])),
                ('precio_unitario', models.DecimalField(decimal_places=2, help_text='Precio unitario al momento del pedido.', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('material', models.ForeignKey(help_text='Material solicitado.', on_delete=django.db.models.deletion.PROTECT, related_name='detalles_pedidos_gestion', to='usuarios.materialconstruccion')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='gestion_pedidos.solicitudpedido')),
            ],
            options={
                'verbose_name': 'Detalle de Solicitud de Pedido',
                'verbose_name_plural': 'Detalles de Solicitud de Pedido',
                'db_table': 'gestion_detalle_pedido',
            },
        ),
    ]
