# Generated by Django 6.0.6 on 2026-06-21 18:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("gestion_pedidos", "0001_initial"),
        ("usuarios", "0002_alter_vehiculo_estado"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Pedido",
            new_name="SolicitudPedido",
        ),
        migrations.RenameModel(
            old_name="DetallePedido",
            new_name="DetalleSolicitudPedido",
        ),
    ]
