# Generated by Django 6.0.6 on 2026-06-18 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ia', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversationhistory',
            name='context_metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Metadatos del contexto de la conversación'),
        ),
        migrations.AlterField(
            model_name='conversationmessage',
            name='model_used',
            field=models.CharField(blank=True, help_text='Modelo de IA usado', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='conversationmessage',
            name='prompt_used',
            field=models.TextField(blank=True, help_text='Prompt usado para generar esta respuesta', null=True),
        ),
        migrations.AlterField(
            model_name='conversationmessage',
            name='response_time',
            field=models.FloatField(blank=True, help_text='Tiempo de respuesta en segundos', null=True),
        ),
    ]
