# Generated by Codex on 2026-07-09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("compras", "0003_alter_detallecompra_cantidad_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="proveedormaterial",
            old_name="precio_proveedor",
            new_name="precio_actual",
        ),
        migrations.AddField(
            model_name="proveedormaterial",
            name="fecha_actualizacion",
            field=models.DateTimeField(auto_now=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
