# Generated by Django 5.1.5 on 2026-08-25 00:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0005_alter_compra_proveedor_alter_compra_usuario_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='compra',
            options={'ordering': ['-fecha_compra'], 'permissions': (('aprobar_compra', 'Puede aprobar compras'), ('gestionar_proveedor', 'Puede gestionar proveedores'))},
        ),
    ]
