# Generated by Django 5.1.5 on 2026-09-09 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0002_add_integrity_constraints'),
        ('compras', '0006_alter_compra_options'),
    ]

    operations = [
    ]
