# Generated by Django 5.2.8 on 2026-09-24 21:24

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '__first__'),
        ('compras', '0007_merge_20260909_0900'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('codigo_proveedor', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_empresa', models.CharField(max_length=150)),
                ('nit', models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator('^[0-9 ]+$', message='Este campo solo puede contener números y espacios.')])),
                ('contacto_nombre', models.CharField(blank=True, max_length=150)),
                ('telefono', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^[0-9 ]+$', message='Este campo solo puede contener números y espacios.')])),
                ('correo', models.EmailField(blank=True, max_length=254)),
                ('direccion', models.CharField(blank=True, max_length=255)),
                ('ciudad', models.CharField(blank=True, max_length=100)),
                ('categoria', models.CharField(blank=True, default='General', max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('sincronizado', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Proveedores',
                'db_table': 'proveedor',
            },
        ),
        migrations.AlterField(
            model_name='detallecompra',
            name='material',
            field=models.ForeignKey(db_column='cod_material', on_delete=django.db.models.deletion.PROTECT, to='catalogo.materialconstruccion'),
        ),
        migrations.AlterField(
            model_name='proveedormaterial',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='proveedores_ofertantes', to='catalogo.materialconstruccion'),
        ),
        migrations.AlterField(
            model_name='compra',
            name='proveedor',
            field=models.ForeignKey(db_column='codigo_proveedor', on_delete=django.db.models.deletion.PROTECT, to='compras.proveedor'),
        ),
        migrations.AlterField(
            model_name='proveedormaterial',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materiales_ofertados', to='compras.proveedor'),
        ),
    ]
