# Generated by Django 5.1.5 on 2026-08-11 15:42

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historial', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historial',
            options={'ordering': ['-fecha'], 'verbose_name': 'Historial de Actividad', 'verbose_name_plural': 'Historial de Actividades'},
        ),
        migrations.AddField(
            model_name='historial',
            name='fecha',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha'),
        ),
        migrations.AddField(
            model_name='historial',
            name='ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='Dirección IP'),
        ),
        migrations.AddField(
            model_name='historial',
            name='registro_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='ID del Registro'),
        ),
        migrations.AddField(
            model_name='historial',
            name='tabla',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Tabla'),
        ),
        migrations.AlterField(
            model_name='historial',
            name='descripcion',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción detallada'),
        ),
        migrations.AlterField(
            model_name='historial',
            name='elemento_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ID Legacy'),
        ),
        migrations.AlterField(
            model_name='historial',
            name='fecha_hora',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Fecha y Hora'),
        ),
        migrations.AlterField(
            model_name='historial',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='historial',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Legacy'),
        ),
        migrations.AlterField(
            model_name='historial',
            name='modulo',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Módulo'),
        ),
        migrations.AlterField(
            model_name='historial',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auditoria', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AlterModelTable(
            name='historial',
            table='historial',
        ),
    ]
