# Generated by Django 5.1.5 on 2026-07-08 22:10

import django.core.validators
import ordenes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallepedido',
            name='precio_unitario',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='fecha_entrega_programada',
            field=models.DateTimeField(blank=True, null=True, validators=[ordenes.models.validar_fecha_no_pasada]),
        ),
    ]
