# Generated by Django 5.1.5 on 2026-08-11 15:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_alter_cliente_options_cliente_direccion_and_more'),
        ('ordenes', '0004_alter_pedido_estado'),
        ('usuarios', '0007_rol_usuariorol_vehiculo_catalogo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='entrega',
            name='conductor_usuario',
            field=models.ForeignKey(blank=True, db_column='conductor_usuario_id_legacy', limit_choices_to={'rol': 'conductor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pedido',
            name='catalogo',
            field=models.ForeignKey(blank=True, db_column='codigo_catalogo', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos', to='usuarios.catalogo'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='conductor_usuario_legacy',
            field=models.ForeignKey(blank=True, db_column='conductor_usuario_id_legacy', limit_choices_to={'rol': 'conductor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos_conductor_legacy', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='detallepedido',
            name='material',
            field=models.ForeignKey(db_column='cod_material', on_delete=django.db.models.deletion.PROTECT, to='usuarios.materialconstruccion'),
        ),
        migrations.AlterField(
            model_name='entrega',
            name='conductor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entregas', to='usuarios.conductor'),
        ),
        migrations.AlterField(
            model_name='entrega',
            name='vehiculo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entregas', to='usuarios.vehiculo'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='conductor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos_asignados', to='usuarios.conductor'),
        ),
        migrations.AddConstraint(
            model_name='detallepedido',
            constraint=models.CheckConstraint(condition=models.Q(('cantidad__gt', 0)), name='chk_detalle_pedido_cantidad_gt_0'),
        ),
        migrations.AddConstraint(
            model_name='detallepedido',
            constraint=models.CheckConstraint(condition=models.Q(('precio_unitario__gte', 0)), name='chk_detalle_pedido_precio_unitario_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='detallepedido',
            constraint=models.UniqueConstraint(fields=('pedido', 'material'), name='uq_detalle_pedido_pedido_material'),
        ),
        migrations.AddConstraint(
            model_name='pedido',
            constraint=models.CheckConstraint(condition=models.Q(('total__gte', 0)), name='chk_pedido_total_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='pedido',
            constraint=models.CheckConstraint(condition=models.Q(('precio__gte', 0), ('precio__isnull', True), _connector='OR'), name='chk_pedido_precio_gte_0'),
        ),
    ]
