# Generated by Django 5.1.5 on 2026-08-11 21:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0005_entrega_conductor_usuario_pedido_catalogo_and_more'),
        ('usuarios', '0007_rol_usuariorol_vehiculo_catalogo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrega',
            name='conductor_usuario',
            field=models.ForeignKey(blank=True, db_column='entrega_conductor_usuario_id', limit_choices_to={'rol': 'conductor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='catalogo',
            field=models.ForeignKey(blank=True, db_column='pedido_codigo_catalogo', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos', to='usuarios.catalogo'),
        ),
    ]
