# Generated by Django 5.1.5 on 2026-08-25 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0006_fix_db_column_duplicados'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entrega',
            options={'ordering': ['-fecha_salida'], 'permissions': (('registrar_entrega', 'Puede registrar entregas'), ('confirmar_entrega', 'Puede confirmar entregas'))},
        ),
        migrations.AlterModelOptions(
            name='pedido',
            options={'ordering': ['-fecha_solicitud'], 'permissions': (('aprobar_pedido', 'Puede aprobar pedidos'), ('autorizar_despacho', 'Puede autorizar despacho'), ('asignar_vehiculo', 'Puede asignar vehículo a entrega'))},
        ),
    ]
