# Generated by Django 5.1.5 on 2026-09-09 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0003_conductor_fk_to_conductor'),
        ('ordenes', '0007_alter_entrega_options_alter_pedido_options'),
    ]

    operations = [
    ]
