# Generated by Django 5.1.5 on 2026-09-09 15:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0008_merge_20260909_0900'),
        ('usuarios', '0011_alter_materialconstruccion_catalogo'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='pedido',
            name='chk_pedido_precio_gte_0',
        ),
        migrations.AlterField(
            model_name='entrega',
            name='conductor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entregas', to='usuarios.conductor'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='conductor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos_asignados', to='usuarios.conductor'),
        ),
    ]
