# Generated by Django 5.1.5 on 2026-09-09 15:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_cliente_gasto_acumulado'),
        ('ordenes', '0009_remove_pedido_chk_pedido_precio_gte_0_and_more'),
        ('usuarios', '0011_alter_materialconstruccion_catalogo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='pedido',
            constraint=models.CheckConstraint(condition=models.Q(('precio__gte', 0), ('precio__isnull', True), _connector='OR'), name='chk_pedido_precio_gte_0'),
        ),
    ]
